dist: xenial
sudo: required
language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
before_install:
  - curl -LO https://github.com/seccomp/libseccomp/releases/download/v2.4.1/libseccomp-2.4.1.tar.gz
  - tar xf libseccomp-2.4.1.tar.gz
  - cd libseccomp-2.4.1 && ./configure && sudo make install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
